Controllers/FormManageController.cs
using CoreWebApp.Models;
using CoreWebApp.Services;
using CoreWebApp.Models.ECRS;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static System.Net.WebRequestMethods;
using System.Threading.Tasks;

namespace CoreWebApp.Controllers
{
    [Authorize]
    public class FormManageController : Controller
    {
        private readonly ReadDTApiClient _api;
        private readonly ILogger<FormManageController> _logger;

        public FormManageController(ReadDTApiClient api, ILogger<FormManageController> logger)
        {
            _api = api;
            _logger = logger;
        }

        public IActionResult Index()
        {
            // ...組 model，可忽略
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                return PartialView("Index" /*, model */);

            return View(/* model */);
        }

        public async Task<IActionResult> FormQryByPJ()
        {
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                return PartialView("FormQryByPJ");

            return View();
        }

        public async Task<IActionResult> FormEditer(string cities)
        {
            //return View();
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                var DeptDt = await Get_系統_部門表(string.Empty);
                ViewBag.DeptList = DeptDt;
                return PartialView("FormEditer");
            }

            return View();
        }

        //[HttpGet]
        public async Task<IActionResult> FormAdd()
        {
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                return PartialView("FormAdd");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> FormAdd(string FormName)
        {
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                ViewData["FormName"] = string.IsNullOrEmpty(FormName) ? string.Empty : FormName;
                return PartialView("FormAdd");
            }

            return View();
        }





        public async Task<List<系統_部門表>> Get_系統_部門表(string cities)
        {
            var deptDt = await _api.Query_系統_部門表(cities);

            try
            {
                return await _api.Query_系統_部門表(cities);
            }
            catch (Exception ex)
            {
                throw;
            }

            return deptDt;
        }


    }
}

Views/FormManage/FormQryByPJ.cshtml
@{
    ViewData["Title"] = "表單管理-專案查詢";
}


<h1 class="main-title">
    <span id="ctl00_ContentPlaceHolder1_UC_NodeName_lblNodeName">@ViewData["Title"]</span>
</h1>
<div id="ctl00_ContentPlaceHolder1_Panel1">

    <input type="hidden" name="ctl00$ContentPlaceHolder1$GroupId" id="ctl00_ContentPlaceHolder1_GroupId" value="4">
    <div class="tb-single-rwd">
        <div class="td hd">
            <input id="radioCustom" type="radio" name="groupType" checked>自訂表單名稱</input>
        </div>
        <div class="td">
            <input id="FormName" type="text" placeholder="高雄市食品工廠" class="form-control">
        </div>
    </div>
    <div class="tb-single-rwd">
        <div class="td hd">
            <input id="radioProject" type="radio" name="groupType">專案名稱</input>
        </div>
        <div class="td">
            <input id="PJName" type="text" class="form-control" placeholder="高雄市食品工廠已逾兩年未執行稽查通知群組" />
        </div>
        <div class="td hd">
            建立單位：
        </div>
        <div class="td">
            <select id="Select1">
                <option>全部</option>
            </select>
        </div>
    </div>

    <div class="btn-area" style="margin-left:80%;">
        <span style="vertical-align: top;">
            <button type="button" class="btn btn-primary">搜尋</button>
            <input id="btnClear" type="button" class="btn btn-primary" onclick="qry_clear()" value="清除" />
        </span>
    </div>

    <div class="tb-single-rwd">
        <div class="td">
            <ul class="inline-block">
                <li style="width: 300px;" class="text-center">
                    <span style="font-weight: bold;">搜尋結果</span>
                </li>
                <li style="width: 300px;"></li>
                <li style="width: 300px; margin-left: 90px" class="text-center">
                    <span style="font-weight: bold;">已選擇專案</span>
                </li>
            </ul>
        </div>
    </div>
    <div class="tb-single-rwd">
        <div class="td hd"></div>
        <div class="td">
            <ul class="inline-block">
                <li>
                    <select size="4" name="ctl00$ContentPlaceHolder1$LBSelect" multiple="multiple" id="ctl00_ContentPlaceHolder1_LBSelect" class="form-control" style="width: 300px; height: 400px">
                        <option value="S221178181">鄭慧君</option>

                    </select>
                </li>
                <li>
                    <div class="btn-group" style="position: absolute; top: 45%">
                        <input type="submit" name="ctl00$ContentPlaceHolder1$right" value="-&gt;" id="ctl00_ContentPlaceHolder1_right" class="btn btn-primary-line">
                        <input type="submit" name="ctl00$ContentPlaceHolder1$left" value="&lt;-" onclick="return chkMail();" id="ctl00_ContentPlaceHolder1_left" class="btn btn-primary-line">
                    </div>
                </li>
                <li>
                    <select size="4" name="ctl00$ContentPlaceHolder1$LBUnselect" multiple="multiple" id="ctl00_ContentPlaceHolder1_LBUnselect" class="form-control" style="width: 300px; height: 400px; margin-left: 90px">
                        <option value="V221289119">包裝飲料產品之咖啡因標示稽查（FDA）</option>
                        <option value="X220084101">超商，速食樂（FDA）</option>
                        <option value="T222133276">真空包裝即食飲品販售溫度稽查1（FDA）</option>
                        <option value="T222211257">網路食品（FDA）</option>
                        <option value="T223161916">市售禽肉來源及標示與其衛生安全（FDA）</option>
                    </select>
                </li>
            </ul>
        </div>
    </div>
    <div class="btn-area">
        <span style="vertical-align: top;">
            @* <button type="button" class="btn btn-primary" onclick="window.history.go(-1);">儲存</button> *@
            @* <a asp-action="FormAdd" asp-controller="FormManage">儲存</a> *@
            <button type="button" id="btnLoadForm" class="btn btn-primary" data-url="@Url.Action("FormAdd", "FormManage")" onclick="loadForm()">儲存</button>
            <button type="button" class="btn btn-primary" onclick="window.history.go(-1);">取消</button>
        </span>
    </div>

    <div id="formAddHost"></div>

</div>

Views/FormManage/Index.cshtml
@{
    ViewData["Title"] = "首頁";
    var username = ViewBag.Username as string ?? "";
    var loginSuccess = TempData["LoginSuccess"] as string;
    var loginTime = ViewBag.loginTime as string ?? DateTime.Now.ToString("yyyy/MM/DD HH:mm:ss");
    var displayName = Context.Session.GetString("DisplayName");
}


<div class="wellcome">
    <div class="row">
        <div class="col col-sm-12">
            <h3>
                <p>
                    親愛的
                        @* <asp:Label runat="server" ID="lblUserName"></asp:Label>*@
                        @displayName
                    您好！​
                </p>
                <p>
                    歡迎使用 <span class="big">電子稽查記錄系統</span>
                </p>
                <p class="date">
                    成功登入時間 : @loginTime
                </p>
            </h3>
            @*<div class="info">
                <a href="javascript:;" class="btn btn-default" data-toggle="collapse" data-target="#wait-list">待辦清單 <span class="caret"></span>
                </a>
                <a href="#" onclick="ChgPwd();">
                    <input type="button" class="btn btn-password" runat="server" id="btnChgPwd" value="變更密碼" /></a>
                <small>提醒您，透過網站右上角下拉選項，可快速切換您常用的系統​</small>
            </div>*@
        </div>
    </div>
</div>